app = "tvc-app"
primary_region = "iad"

[build]

[deploy]
  release_command = ""

[run]
  cmd = "node dist/server/main.js"
  max_concurrency = 1

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2

[[mounts]]
  source = "data"
  destination = "/data"

[env]
  PORT = "3123"
  NODE_ENV = "production"
  DATA_DIR_PATH = "/data"
